## Vectors and matrices 


Points in a plane in the real space are given by pairs $(x,y)$ in $\mathbb{R}^2$

<img src="Vektor2D.jpg" width="400"/>

In three dimensions, we write $(x,y,z)$ in $\mathbb{R}^3$ and in $n$ dimensions we write  $(x_1,x_2,\dots ,x_n )$ in $\mathbb{R}^n$

Usually, we consider column vectors and, instead of separating the elements by a komma, we write: 
$ \begin{pmatrix} x_1 \\ x_2  \end{pmatrix} $ in two dimensions, respectively $$ \begin{pmatrix} x_1 \\ x_2  \\ x_3  \\  \vdots \\ x_n \end{pmatrix} $$  in the n-dimensional real space.

We can add two vectors  by adding elementwise:

$$ \begin{pmatrix} a_1 \\ a_2  \\ a_3  \\  \vdots \\ a_n \end{pmatrix} + \begin{pmatrix} b_1 \\ b_2  \\ b_3  \\  \vdots \\ b_n \end{pmatrix} =  \begin{pmatrix} a_1+b_1 \\ a_2+ b_2  \\ a_3+b_3  \\  \vdots \\ a_n+b_n \end{pmatrix} $$ 


<img src="Vektoraddition.jpg" width="400"/>

Multiplication of a vector with a real valued scalar $\lambda$:

$$k \cdot \begin{pmatrix} a_1 \\ a_2  \\ a_3  \\  \vdots \\ a_n \end{pmatrix}
=  \begin{pmatrix} \lambda \cdot a_1 \\ k \cdot  a_2  \\  k \cdot a_3  \\  \vdots \\ k \cdot a_n \end{pmatrix} $$

Example: 

$$ 3 \cdot \begin{pmatrix} 1 \\ 2  \\ 3   \end{pmatrix}
=  \begin{pmatrix} 3 \\6  \\  9 \end{pmatrix} $$


<img src="Multiplikation_mit_Skalar.jpg" width="400"/>

The scalarproduct of two vectors is needed, if you want to calculate distances or lengths in the plane or a higher dimensional space. The scalar product of the vectors $\vec{a}$ and  $\vec{b}$ is given by: 

$$
\langle \vec{a},\vec{b} \rangle =  
\langle  \begin{pmatrix} a_1 \\ a_2  \\ a_3 \\ \vdots  \\ a_n  \end{pmatrix},
 \begin{pmatrix} b_1 \\ b_2  \\ a_3 \\ \vdots  \\ a_n  \end{pmatrix}\rangle = 
 a_1 \cdot b_1 + a_2 \cdot b_2 + \dots + a_n \cdot b_n   $$

Note that the scalar product of two vectors that are perpendicular is zero. This is always a great test, if you found an orthogonal (coordinate) system. 

The eucledian length of a vector can be calculated by the root of the scalar product:

$$ \vert\vec{a} \vert = \sqrt{  \langle \vec{a}, \vec{a} \rangle }
=
\sqrt{  
\langle 
\begin{pmatrix}  a_1 \\ a_2  \\ a_3 \\ \vdots  \\ a_n    \end{pmatrix},
  \begin{pmatrix}  a_1 \\ a_2  \\ a_3 \\ \vdots  \\ a_n    \end{pmatrix} 
  \rangle } = \sqrt{  a_1^2+a_2^2+\cdots + a_n^2 }  $$

Let us consider the vector $\begin{pmatrix} 1 \\ 0  \end{pmatrix}$. This is just the one on the x-axis and the y-value is 0. Therefore, we already know, it should have length = 1. Lets test this: 

 $$\sqrt{  \langle \begin{pmatrix} 1 \\ 0  \end{pmatrix} \rangle } = \sqrt{  1^2+0^2+0^2 } = 1  $$

### Matrices

Matrices are helpful, if we want to store a lot of data or simplify sets of e.g. linear equations.
Consider the following set of linear equations: 

$$ a_{11} x_1 + a_{12} x_2 + a_{13} x_2 = b_1    $$
$$ a_{21} x_1 + a_{22} x_2 + a_{23} x_2 = b_2    $$
$$ a_{31} x_1 + a_{32} x_2 + a_{33} x_2 = b_3    $$

Let us assume that you know the coefficients $a_{ij}$ and $b_i$, $i=1,2,3$ and you are looking for the $x_1,x_2,x_3$ satisfiying the relations given in these three equations. 

You can first write the coefficients $a_{ij}$ in a matrix and $b_1,b_2,b_3$ in a vector, and $ x_1,x_2,x_3 $ in a vector, too:

$$ A:= \begin{pmatrix} a_{11} & a_{12} & a_{13} \\
                   a_{21} & a_{22} & a_{23} \\
                   a_{31} & a_{32} & a_{33} \\
\end{pmatrix}, \, \
b= \begin{pmatrix} b_1 \\
                b_2 \\
                b_3 \\
\end{pmatrix}, \, \
x = \begin{pmatrix} x_1 \\
                x_2 \\
                x_3 \\
\end{pmatrix}
$$
and write the set of equations as: 
$$ A \cdot x = b $$



Remark: Regarding neural networks, you know the x (and maybe the b) and want to find the optimal $a_{ij}$.

##### Matrix multiplication

Two matrices, say $A$ and $B$, are multiplied as follows: 

$$ A \cdot B = 
\underbrace{
\begin{pmatrix} 
                   a_{11} & a_{12} & a_{13} \\
                   a_{21} & a_{22} & a_{23} \\
\end{pmatrix} 
}_{2 \times 3 Matrix}
\cdot 
\underbrace{
\begin{pmatrix} b_{11} & b_{12}  \\
                b_{21} & b_{22}  \\
                b_{31} & b_{32}  \\
\end{pmatrix} 
}_{3 \times 2 Matrix}
=
\underbrace{
\begin{pmatrix}
  a_{11}\cdot  b_{11} + a_{12}\cdot  b_{21} + a_{13}\cdot  b_{31} &
  a_{11}\cdot  b_{12} + a_{12}\cdot  b_{22} + a_{13}\cdot  b_{32} \\
  a_{21}\cdot  b_{11} + a_{22}\cdot  b_{21} + a_{23}\cdot  b_{31} &
  a_{21}\cdot  b_{12} + a_{22}\cdot  b_{22} + a_{23}\cdot  b_{32} \\
\end{pmatrix}
}_{2 \times 2 Matrix}
$$

$A$ is a $2 \times 3$ Matrix, which means that it has 2 rows and 3 columns. $B$ is a $3 \times 2$ Matrix, which means that it has 3 rows and 2 columns. If you want to multiply two matrices, the number of columns of batrix A needs to be equals to the number of rows of matrix B. The outcome matrix is of the size 'the number of rows of matrix A $\times$ the number of columns of matrix B'. The dimensionality is always a good check, if the matrix multiplication is correct. 



### Vectors and matrices in Python



In [1]:
# Numpy and Scipy --> sehr hilfreiche Module
import numpy as np

In [2]:
x = np.arange(1,10)

In [3]:
print(x)

[1 2 3 4 5 6 7 8 9]


In [4]:
# mit Schrittweite: 
x = np.arange(1,10,3)
print(x)

[1 4 7]


In [5]:
## Array --> Müssen vom Datentyp float oder int sein

x = np.array([1,2,3])

In [6]:
x

array([1, 2, 3])

In [7]:
## Matritzen: 
A = np.array([[1, 2], [3, 4],[5, 6]])

Siehe zum Beispiel: https://www.programiz.com/python-programming/matrix

In [8]:
## Wie groß ist unser Array?

A.shape

(3, 2)

Das Bedeutet: 3 Zeilen, 2 Spalten, test:

In [9]:
A

array([[1, 2],
       [3, 4],
       [5, 6]])

Auf das Element in der zweiten Zeile und ersten Spalte zugreifen: (Erinnerung: in Python beginnen wir immer mit der 0!):

In [10]:
A[1,0]

3

Wir können Arrays in eine andere Form bringen (np.reshape) und auch verknüpfen (np.concatenate):

In [11]:
## 
a = np.array(range(24))
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


In [12]:
a.reshape(4,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [13]:
x = np.array([1,2,3])
y = np.array([4,5,6])

In [14]:
z = np.concatenate((x,y))

In [15]:
z

array([1, 2, 3, 4, 5, 6])

Arrays mit Nullen oder Einsen initialisieren: 

In [16]:
Nullmatrix = np.zeros((2,3))
print(Nullmatrix)

[[0. 0. 0.]
 [0. 0. 0.]]


In [17]:
Einsmatrix = np.ones((2,3))
print(Einsmatrix)

[[1. 1. 1.]
 [1. 1. 1.]]


#### Rechnen mit Matritzen (und Vektoren)

In [18]:
x = np.array([1,2,3])
y = np.array([4,5,6])

Die arithmetischen Standardoperationen +,-,*,/,** werden emelemntweise angewendet, 

In [19]:
x+y

array([5, 7, 9])

Skalarprodukt: 

In [20]:
np.dot(x,y) 

32

Skalarprodukt von x und y ergibt sich aus: $1*4+2*5+3*6 = 32$

In [21]:
#Matrixprodukt: Matrix-Objekte definieren

x = np.matrix("2 3 ; 3 1")
y = np.matrix("0 1 ; 1 1")

In [22]:
np.matrix(x)*np.matrix(y)

matrix([[3, 5],
        [1, 4]])